services:
  postgres:
    image: postgres:15
    container_name: litestar_lab3_db
    environment:
      POSTGRES_DB: litestar_lab3
      POSTGRES_USER: litestar_user
      POSTGRES_PASSWORD: litestar_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: